# docker-compose.yml
services:
  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/zapzap:/app/zapzap
      - ./data/.ollama:/root/.ollama
    restart: always
