# docker-compose.yml
services:
  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ./data/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
